included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_first_not_nil
  - discarded_notification_center_observer
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - modifier_order
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - yoda_condition

line_length:
  warning: 120
  error: 140
  ignores_urls: true
  ignores_comments: false

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 300
  error: 450

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 15
  error: 25
  ignores_case_statements: true

identifier_name:
  min_length:
    warning: 2
    error: 1
  excluded:
    - id
    - i
    - j
    - x
    - y
    - z
