disabled_rules:
  - closure_parameter_position
  - function_parameter_count
  - identifier_name
  - nesting
  - notification_center_detachment
  - todo
  - type_name

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - closure_end_indentation
  - closure_spacing
  - explicit_init
  - implicit_return
  - literal_expression_end_indentation
  - modifier_order
  - operator_usage_whitespace
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - array_init
  - attributes
  - closure_body_length
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - empty_string
  - empty_xctest_method
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - identical_operands
  - last_where
  - let_var_whitespace
  - lower_acl_than_parent
  - missing_docs
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - private_action
  - required_enum_case
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher

cyclomatic_complexity:
  ignores_case_statements: true

line_length:
  error: 120
file_length: 500
closure_body_length: 50
